name: postgres_conector
description: A library for connecting to and querying PostgreSQL databases.
version: 1.0.0-dev.1
# homepage: https://www.example.com
repository: https://github.com/daniarmas/postgres-conector

environment:
  sdk: '>=2.13.4 <3.0.0'


dependencies:
  path: ^1.8.0
  postgres: ^2.4.0
  uuid: ^3.0.4

dev_dependencies:
  # dart run build_runner build
  build_runner: ^2.0.5
  lints: ^1.0.1
  mockito: ^5.0.10
  test: ^1.17.9
